apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-frontend
  template:
    metadata:
      labels:
        app: contact-frontend
    spec:
      containers:
      - name: frontend
        image: 203733861292.dkr.ecr.ap-south-1.amazonaws.com/contact-backend
        ports:
        - containerPort: 80