apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 203733861292.dkr.ecr.ap-south-1.amazonaws.com/contact-backend
        ports:
        - containerPort: 8080